### ISSUE TITLE
Frontend connection to Backend

### ISSUE THREAD

**Issue by jjordanzlatanov** [jjordanzlatanov/diploma-project#11]
**Description**
Add connection between the forms of the frontend pages and the backend server using Thymeleaf

**Tasks**
- [x] Add classes with appropriate annotations regarding the MySQL database
- [x] Add Thymeleaf to the HTML
- [x] Create UserRepository for handling CRUD operations
