### ISSUE TITLE
Create confirmation email

### ISSUE THREAD

**Issue by jjordanzlatanov** [jjordanzlatanov/diploma-project#14]
**Description**
Send a confirmation email to the user upon registry to their email address, containing a link to confirm their account

**Tasks**
- [x] Add HTML page to show the user their account has been successfully created and they should check their email
- [x] Add token creation/SQL mechanism, make it expire in 24 hours
- [x] Add the ability to send the confirmation email to the client

**Comment by jjordanzlatanov** [comment]
Temporary created account is also removed when token is expired.
