### ISSUE TITLE
Add ESC screen UI

### ISSUE THREAD

**Issue by jjordanzlatanov** [jjordanzlatanov/diploma-project#32]
**Description**
Add a dimming screen on "ESC" button press with "Logout" and "Controls" options. This menu should act as a toggle.

**Tasks**
- [ ] Add dimmed window
- [ ] Add menu with user interaction
- [ ] Add logout button which redirects to home screen
- [ ] Add control button which reveals new menu with all controls
