### ISSUE TITLE
Add game logic

### ISSUE THREAD

**Issue by jjordanzlatanov** [jjordanzlatanov/diploma-project#35]
**Description**
Add game logic on the backend.

**Tasks**
- [x] Add service for managing game sessions (threads)
- [x] Add ability to load/add objects to the session
- [ ] Add "tick" function to game objects
