### ISSUE TITLE
Add ability to delete game objects

### ISSUE THREAD

**Issue by jjordanzlatanov** [jjordanzlatanov/diploma-project#42]
**Description**
Add the ability to delete game objects. After deletion, the tiles under the object are refreshed.

**Tasks**
- [ ] Delete object from server memory
- [ ] Delete object from database storage
- [ ] Refresh tiles under the object
